name: Continuous Integration
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Probe rust cache
        uses: Swatinem/rust-cache@v2
      - name: Build WASM artifact
        run: cargo build --release --target wasm32-unknown-unknown
        working-directory: ./wasm
      - name: Copy WASM artifact
        run: cp -f ./wasm/target/wasm32-unknown-unknown/release/based.wasm ./src/based.wasm

      - name: Upload WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: based.wasm
          path: ./src/based.wasm

      - name: Probe runner package cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cargo
          version: 1.0

      - name: Install typst-test from GitHub
        uses: baptiste0928/cargo-install@v3
        with:
          crate: typst-test
          git: https://github.com/tingerrr/typst-test.git
          tag: ci-semi-stable

      - name: Setup typst
        uses: typst-community/setup-typst@v3

      - name: Run test suite
        run: typst-test run
